# Generated by Django 5.2.5 on 2025-08-28 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Artist')),
            ],
            options={
                'verbose_name': 'Artist',
                'verbose_name_plural': 'Artists',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Song title')),
            ],
            options={
                'verbose_name': 'Song',
                'verbose_name_plural': 'Songs',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Album title')),
                ('release_year', models.PositiveIntegerField(verbose_name='Release year')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='music.artist', verbose_name='Artist')),
            ],
            options={
                'verbose_name': 'Album',
                'verbose_name_plural': 'Albums',
                'ordering': ['release_year', 'title'],
            },
        ),
        migrations.CreateModel(
            name='AlbumSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_number', models.PositiveIntegerField(verbose_name='Track number')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_songs', to='music.album')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_songs', to='music.song')),
            ],
            options={
                'verbose_name': 'Song in the album',
                'verbose_name_plural': 'Songs in albums',
                'ordering': ['track_number'],
                'unique_together': {('album', 'track_number')},
            },
        ),
        migrations.AddField(
            model_name='album',
            name='songs',
            field=models.ManyToManyField(related_name='albums', through='music.AlbumSong', to='music.song', verbose_name='Songs'),
        ),
    ]
